### ISSUE TITLE
Finalize the engine rebranding

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#1650]
Spring is clearly dead, all sane people migrated from there, so by now the naming is more a liability than advantage (if were were advantages to start with). This is low prio, but good to have gradually:

```[tasklist]
### TODO
- [ ] Duplicate all `Spring.` calls with `Recoil.` calls in Lua space. All new call outs should use `Recoil.` semantic.
- [ ] Change all titles from Spring to Recoil in various places, that are displayed to the user.
- [ ] Duplicate output binary names, release both `recoil*` and `spring*` binaries. 
- [ ] Leave Spring engine versioning (will probably stay forever as 105 and/or BAR105), and add another versioning scheme for Recoil.
- [ ] Change namespaces and function names within the engine to use Recoil
- [ ] The comments saying "this file is part of Spring project", can this be changed or only amended? In any case do so.
- [ ] Not strictly rebranding related, but would be great to update start menus to use new UI (esp after RmlUI work is merged). The current one is quite horrible.
- [ ] This one is under the question mark. https://github.com/beyond-all-reason has been a great place for us and there were no conflicts of interest as Recoil treated all of its users fairly I think, still maybe a good move is to at least mirror the repo to https://github.com/recoilengine, so people know it's not only a BAR engine.
```

**Comment by lhog** [comment]
Meh that was supposed to look differently, anyway the content is more important than its representation.

**Comment by sprunk** [comment]
> Duplicate all `Spring.` calls with `Recoil.` calls in Lua space. All new call outs should use `Recoil.` semantic.

Just change it straight up, gameside back-compat is a trivial one liner: `Spring = Recoil or Spring` at Lua entry points.

> The comments saying "this file is part of Spring project", can this be changed or only amended?

Spring still owns copyright for those files, and GPL article 1 says one must "appropriately publish on each copy an appropriate copyright notice (...) keep intact all the notices that refer to this License". This sounds like they must stay.

**Comment by lhog** [comment]
Cool, thanks for the clarification, we can amend the statement then.
With Spring/Recoil tables I don't want to push it too hard on existing games, but I agree this can be a way forward too.

**Comment by 12345swordy** [comment]
Is the buildbot folder even needed for coil?
